### ISSUE TITLE
Possible to recognize whatever TOC convention appears in the document

### ISSUE THREAD

**Issue by korm** [Aidurber/obsidian-plugin-dynamic-toc#11]
@Aidurber added a couple of useful conventions for TOC markup.

I wonder if it would be possible if the plugin would add a TOC when  _**any**_ of the recognized conventions were present in the document.  So, if I imported a file from DEVONthink and used the DEVONthink `{{toc}}` syntax it would be recognized, and then if I imported a file from some place else that used a different syntax, then the plugin would recognize that.  This way we wouldn't have to be limited to just one configured convention.   This would make the plugin "universally" functional.

**Comment by Aidurber** [comment]
I think that would be possible. I think we would have to add a new option "Support all renderers" to make it opt-in. Good suggestion, I'll add it to the backlog!

**Comment by Aidurber** [comment]
This should be live in version 0.0.13
