### ISSUE TITLE
Plugin no longer working

### ISSUE THREAD

**Issue by swehba** [Aidurber/obsidian-plugin-dynamic-toc#14]
Has something changed recently that could cause the plugin to no longer work? I tried the examples and none of then generate a TOC when I switch to preview for the page/note. It used to work great.

**Comment by Aidurber** [comment]
@swehba I'm unsure if it was the root cause of your issue, but I did find a problem that would cause errors to occur and therefore stop rendering the contents. Please update to 0.0.15, reload obsidian and test it out.
