### ISSUE TITLE
Dynamic Table of Contents: styles.css not found

### ISSUE THREAD

**Issue by gfidias** [Aidurber/obsidian-plugin-dynamic-toc#16]
Dynamic table of contents version 0.0.15

app.js:1 GET https://github.com/aidurber/obsidian-plugin-dynamic-toc/releases/download/0.0.15/styles.css 404
m @ app.js:1
(anonymous) @ app.js:1
window.ajaxPromise @ app.js:1
t.ajaxCorsBypass @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.installPlugin @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
cn @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
**app.js:1 Dynamic Table of Contents: styles.css not found**
VM339:2 Dynamic TOC Loaded

**Comment by Aidurber** [comment]
Minor, it doesn't break anything it's noise.

**Comment by Aidurber** [comment]
Gonna close this, we now have a styles.css file since 0.0.23
