### ISSUE TITLE
Conflict with dataview?

### ISSUE THREAD

**Issue by gfidias** [Aidurber/obsidian-plugin-dynamic-toc#17]
After installing version 0.0.15, pages with dataview blocks don't update or don't display preview at all.

**Comment by Aidurber** [comment]
Can you provide a brief example please?

**Comment by gfidias** [comment]
This block used to produce many results, now it only gets one (see attached image)
 
# Projects

```dataview
table status, priority, file.folder as location
from #project 
sort priority desc
```
![1](https://user-images.githubusercontent.com/23036873/136960926-a9b130b3-7177-4646-be3b-0a5539e706a8.jpg)

Also, I get these errors:

main.ts:32 Uncaught TypeError: Cannot read property 'className' of null
    at EmbeddedCodeTitlePlugin.insertFileNamesIntoCodeBlocks (eval at <anonymous> (app.js:1), <anonymous>:53:60)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:85:61)
    at Function.t.postProcess (app.js:1)
    at t.postProcess (app.js:1)
    at h (app.js:1)
    at e.onRender (app.js:1)
insertFileNamesIntoCodeBlocks @ main.ts:32
eval @ main.ts:74
t.postProcess @ app.js:1
t.postProcess @ app.js:1
h @ app.js:1
e.onRender @ app.js:1
requestAnimationFrame (async)
Xe @ app.js:1
e.queueRender @ app.js:1
e.set @ app.js:1
t.set @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.setMode @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.setState @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.setViewState @ app.js:1
eval @ main.tsx:745
a @ main.tsx:745
eval @ VM307:36262
wrapper @ VM307:54
eval @ VM308:106
S @ VM308:91
eval @ VM340:72
o @ VM340:23
checkCallback @ app.js:1
EE @ app.js:1
e.executeCommandById @ app.js:1
eval @ VM340:72
o @ VM340:23
e.onTrigger @ app.js:1
e.handleKey @ app.js:1
e.onKeyEvent @ app.js:1
Show 16 more frames
render_sync.cjs:10 Uncaught TypeError: Cannot read property 'className' of null
    at EmbeddedCodeTitlePlugin.insertFileNamesIntoCodeBlocks (eval at <anonymous> (app.js:1), <anonymous>:53:60)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:85:61)
    at Function.t.postProcess (app.js:1)
    at t.postProcess (app.js:1)
    at h (app.js:1)
    at e.onRender (app.js:1)
insertFileNamesIntoCodeBlocks @ main.ts:32
eval @ main.ts:74
t.postProcess @ app.js:1
t.postProcess @ app.js:1
h @ app.js:1
e.onRender @ app.js:1
VM427:2 Uncaught (in promise) TypeError: Cannot read property 'toLowerCase' of undefined
    at eval (eval at <anonymous> (app.js:1), <anonymous>:2:3500)
    at Array.find (<anonymous>)
    at Function.findMatch (eval at <anonymous> (app.js:1), <anonymous>:2:3453)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:2:4637)
    at Function.<anonymous> (app.js:1)
    at app.js:1
    at Object.next (app.js:1)
    at app.js:1
    at new Promise (<anonymous>)
    at o (app.js:1)
eval @ VM427:2
findMatch @ VM427:2
eval @ VM427:2
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.renderMarkdown @ app.js:1
eval @ render.ts:30
eval @ tslib.es6.js:76
__awaiter @ tslib.es6.js:72
renderCompactMarkdown @ render.ts:27
eval @ render.ts:177
eval @ tslib.es6.js:76
__awaiter @ tslib.es6.js:72
renderValue @ render.ts:132
eval @ render.ts:74
eval @ tslib.es6.js:76
__awaiter @ tslib.es6.js:72
renderTable @ render.ts:59
eval @ main.ts:615
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
eval @ tslib.es6.js:76
__awaiter @ tslib.es6.js:72
onload @ main.ts:585
e.load @ app.js:1
e.addChild @ app.js:1
addChild @ app.js:1
eval @ main.ts:464
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
eval @ tslib.es6.js:76
__awaiter @ tslib.es6.js:72
onload @ main.ts:447
e.load @ app.js:1
e.addChild @ app.js:1
addChild @ app.js:1
eval @ main.ts:107
eval @ tslib.es6.js:76
__awaiter @ tslib.es6.js:72
eval @ main.ts:68
eval @ main.ts:220
eval @ tslib.es6.js:76
__awaiter @ tslib.es6.js:72
postProcess @ main.ts:195
t.postProcess @ app.js:1
t.postProcess @ app.js:1
h @ app.js:1
e.onRender @ app.js:1
requestAnimationFrame (async)
Xe @ app.js:1
e.queueRender @ app.js:1
e.set @ app.js:1
t.set @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.setMode @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.setState @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.setViewState @ app.js:1
eval @ main.tsx:745
a @ main.tsx:745
eval @ VM307:36262
wrapper @ VM307:54
eval @ VM308:106
S @ VM308:91
eval @ VM340:72
o @ VM340:23
checkCallback @ app.js:1
EE @ app.js:1
e.executeCommandById @ app.js:1
eval @ VM340:72
o @ VM340:23
e.onTrigger @ app.js:1
e.handleKey @ app.js:1
e.onKeyEvent @ app.js:1
Show 32 more frames
main.ts:32 Uncaught TypeError: Cannot read property 'className' of null
    at EmbeddedCodeTitlePlugin.insertFileNamesIntoCodeBlocks (eval at <anonymous> (app.js:1), <anonymous>:53:60)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:85:61)
    at Function.t.postProcess (app.js:1)
    at t.postProcess (app.js:1)
    at h (app.js:1)
    at e.onRender (app.js:1)
insertFileNamesIntoCodeBlocks @ main.ts:32
eval @ main.ts:74
t.postProcess @ app.js:1
t.postProcess @ app.js:1
h @ app.js:1
e.onRender @ app.js:1
requestAnimationFrame (async)
Xe @ app.js:1
e.queueRender @ app.js:1
(anonymous) @ app.js:1
Promise.then (async)
h @ app.js:1
e.onRender @ app.js:1
requestAnimationFrame (async)
Xe @ app.js:1
e.queueRender @ app.js:1
e.set @ app.js:1
t.set @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.setMode @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.setState @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.setViewState @ app.js:1
eval @ main.tsx:745
a @ main.tsx:745
eval @ VM307:36262
wrapper @ VM307:54
eval @ VM308:106
S @ VM308:91
eval @ VM340:72
o @ VM340:23
checkCallback @ app.js:1
EE @ app.js:1
e.executeCommandById @ app.js:1
eval @ VM340:72
o @ VM340:23
e.onTrigger @ app.js:1
e.handleKey @ app.js:1
e.onKeyEvent @ app.js:1
Show 21 more frames
render_sync.cjs:10 Uncaught TypeError: Cannot read property 'className' of null
    at EmbeddedCodeTitlePlugin.insertFileNamesIntoCodeBlocks (eval at <anonymous> (app.js:1), <anonymous>:53:60)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:85:61)
    at Function.t.postProcess (app.js:1)
    at t.postProcess (app.js:1)
    at h (app.js:1)
    at e.onRender (app.js:1)
insertFileNamesIntoCodeBlocks @ main.ts:32
eval @ main.ts:74
t.postProcess @ app.js:1
t.postProcess @ app.js:1
h @ app.js:1
e.onRender @ app.js:1
VM427:2 Uncaught (in promise) TypeError: Cannot read property 'toLowerCase' of undefined
    at eval (eval at <anonymous> (app.js:1), <anonymous>:2:3500)
    at Array.find (<anonymous>)
    at Function.findMatch (eval at <anonymous> (app.js:1), <anonymous>:2:3453)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:2:4637)
    at Function.<anonymous> (app.js:1)
    at app.js:1
    at Object.next (app.js:1)
    at app.js:1
    at new Promise (<anonymous>)
    at o (app.js:1)
eval @ VM427:2
findMatch @ VM427:2
eval @ VM427:2
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.renderMarkdown @ app.js:1
eval @ render.ts:30
eval @ tslib.es6.js:76
__awaiter @ tslib.es6.js:72
renderCompactMarkdown @ render.ts:27
eval @ render.ts:177
eval @ tslib.es6.js:76
__awaiter @ tslib.es6.js:72
renderValue @ render.ts:132
eval @ render.ts:74
eval @ tslib.es6.js:76
__awaiter @ tslib.es6.js:72
renderTable @ render.ts:59
eval @ main.ts:615
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
eval @ tslib.es6.js:76
__awaiter @ tslib.es6.js:72
onload @ main.ts:585
e.load @ app.js:1
e.addChild @ app.js:1
addChild @ app.js:1
eval @ main.ts:464
fulfilled @ tslib.es6.js:73
Promise.then (async)
step @ tslib.es6.js:75
eval @ tslib.es6.js:76
__awaiter @ tslib.es6.js:72
onload @ main.ts:447
e.load @ app.js:1
e.addChild @ app.js:1
addChild @ app.js:1
eval @ main.ts:107
eval @ tslib.es6.js:76
__awaiter @ tslib.es6.js:72
eval @ main.ts:68
eval @ main.ts:220
eval @ tslib.es6.js:76
__awaiter @ tslib.es6.js:72
postProcess @ main.ts:195
t.postProcess @ app.js:1
t.postProcess @ app.js:1
h @ app.js:1
e.onRender @ app.js:1
requestAnimationFrame (async)
Xe @ app.js:1
e.queueRender @ app.js:1
(anonymous) @ app.js:1
Promise.then (async)
h @ app.js:1
e.onRender @ app.js:1
requestAnimationFrame (async)
Xe @ app.js:1
e.queueRender @ app.js:1
e.set @ app.js:1
t.set @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.setMode @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.setState @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.setViewState @ app.js:1
eval @ main.tsx:745
a @ main.tsx:745
eval @ VM307:36262
wrapper @ VM307:54
eval @ VM308:106
S @ VM308:91
eval @ VM340:72
o @ VM340:23
checkCallback @ app.js:1
EE @ app.js:1
e.executeCommandById @ app.js:1
eval @ VM340:72
o @ VM340:23
e.onTrigger @ app.js:1
e.handleKey @ app.js:1
e.onKeyEvent @ app.js:1
Show 32 more frames
VM427:2 Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    at eval (eval at <anonymous> (app.js:1), <anonymous>:2:3500)
    at Array.find (<anonymous>)
    at Function.findMatch (eval at <anonymous> (app.js:1), <anonymous>:2:3453)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:2:4637)
    at Function.t.postProcess (app.js:1)
    at t.postProcess (app.js:1)
    at h (app.js:1)
    at e.onRender (app.js:1)
eval @ VM427:2
findMatch @ VM427:2
eval @ VM427:2
t.postProcess @ app.js:1
t.postProcess @ app.js:1
h @ app.js:1
e.onRender @ app.js:1
requestAnimationFrame (async)
Xe @ app.js:1
e.queueRender @ app.js:1
(anonymous) @ app.js:1
Promise.then (async)
h @ app.js:1
e.onRender @ app.js:1
requestAnimationFrame (async)
Xe @ app.js:1
e.queueRender @ app.js:1
(anonymous) @ app.js:1
Promise.then (async)
h @ app.js:1
e.onRender @ app.js:1
requestAnimationFrame (async)
Xe @ app.js:1
e.queueRender @ app.js:1
e.set @ app.js:1
t.set @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.setMode @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.setState @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.setViewState @ app.js:1
eval @ main.tsx:745
a @ main.tsx:745
eval @ VM307:36262
wrapper @ VM307:54
eval @ VM308:106
S @ VM308:91
eval @ VM340:72
o @ VM340:23
checkCallback @ app.js:1
EE @ app.js:1
e.executeCommandById @ app.js:1
eval @ VM340:72
o @ VM340:23
e.onTrigger @ app.js:1
e.handleKey @ app.js:1
e.onKeyEvent @ app.js:1
Show 27 more frames
render_sync.cjs:10 Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    at eval (eval at <anonymous> (app.js:1), <anonymous>:2:3500)
    at Array.find (<anonymous>)
    at Function.findMatch (eval at <anonymous> (app.js:1), <anonymous>:2:3453)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:2:4637)
    at Function.t.postProcess (app.js:1)
    at t.postProcess (app.js:1)
    at h (app.js:1)
    at e.onRender (app.js:1)
eval @ VM427:2
findMatch @ VM427:2
eval @ VM427:2
t.postProcess @ app.js:1
t.postProcess @ app.js:1
h @ app.js:1
e.onRender @ app.js:1

**Comment by Aidurber** [comment]
I'm still unable to reproduce this, I'm gonna close. Please re-open or create a new ticket if any more issues arise.
