### ISSUE TITLE
Bug: [[_TOC_]] doesn't work

### ISSUE THREAD

**Issue by metruzanca** [Aidurber/obsidian-plugin-dynamic-toc#20]
Trying to get the `[[_TOC_]]` syntax working (which is mentioned in the readme) for compatibility with azure wikis, but it doesn't seem to work. Also in the settings menu it doesn't appear as an option, but looking at the source it appears to be mapped to __TOC__ but still doesn't seem to work 
![image](https://user-images.githubusercontent.com/32832892/140997405-fd9d62a1-1818-45b7-9ab0-dfdae20b40ca.png)

Obsidian: 0.12.19
Plugin: 0.0.16
OS: MacOS Big Sur

**Comment by Aidurber** [comment]
It's `[[__TOC__]]`, double underscores. 

It'd be great if all of these markdown providers shared some syntax 😅 I'll mark this as a feature request and get this in.

**Comment by Aidurber** [comment]
You should find this in 0.0.17. Remember after changing your setting, sometimes that settings requires you to reload obsidian.

**Comment by metruzanca** [comment]
Yeah unfortunately everyone does their own thing instead of following a common syntax :(

Thanks for adding this. Works like a charm now!
