### ISSUE TITLE
Add entry for command palette

### ISSUE THREAD

**Issue by mahoromax** [Aidurber/obsidian-plugin-dynamic-toc#22]
I keep forgetting how this TOC is embedded (on other platforms I need to use [[_TOC_]] or others)

So I think - especially for users new to markdown - it would be great to be able to open  the 'Command Palette' and add the TOC-entry like that.

It could also give an additional entry to help with the options, but I don't have an idea how that could be realized (except by pasting all options as comments)

**Comment by Aidurber** [comment]
Cool suggestion!

I think we'd need multiple commands or even like a drilldown, unsure if we get that out of the box: 

Dynamic TOC - Insert Table of Contents -> Code block -> `your selected external renderer`

If you have "Support all renderers" selected, the list will list all of the supported patterns. 

Yes, I'm liking this. I'll look into it.

**Comment by Aidurber** [comment]
Released in 0.0.18
