### ISSUE TITLE
support the pane view

### ISSUE THREAD

**Issue by guocailee** [Aidurber/obsidian-plugin-dynamic-toc#25]
Thank you for your awsome work.
Will this plugin support pane view in the future？

If not, may I make pull request to suppot it?

**Comment by Aidurber** [comment]
I'm not entirely sure what you mean, if you mean adding something to the sidebar, you can already do this in Obsidian with Core Plugins -> Outline

![2021-12-05 15_18_59-Personal - Obsidian v0 12 19](https://user-images.githubusercontent.com/5732291/144752561-42c86f94-5361-49c5-84a4-d47043250e49.jpg)
![2021-12-05 15_19_08-Personal - Obsidian v0 12 19](https://user-images.githubusercontent.com/5732291/144752563-3cff8f2f-42a9-49c9-a3e9-f87ce0cfcca7.jpg)

**Comment by guocailee** [comment]
Thanks, OutLine do it what i wanted.
