### ISSUE TITLE
Incorrect formatting when heading is an internal link with a custom name

### ISSUE THREAD

**Issue by SebMoore** [Aidurber/obsidian-plugin-dynamic-toc#28]
Obsidian provides support for creating internal links and displaying text for this link that is different to the name of the note you are linking to.
For example:
[[Example Link]] renders as <ins>Example Link</ins>, and links to the file "Example Link"
[[Example Link|Alt Text]] renders as <ins>Alt Text</ins>, but links to the same file, "Example Link".
This is useful for creating readable links where the actual note file may have a long and complex name.
Unfortunately, when I create a heading entitled [[Example Link|Alt Text]], dynamic-toc renders it as <ins>Alt Text|Example Link|Alt Text</ins> which kind of defeats the point of using these kind of internal links in the first place. 
Here's a screenshot to show what I mean:
![dynamic-toc-issue](https://user-images.githubusercontent.com/74476668/146895912-1144fc9b-17e6-4662-a147-702fbe612d73.png)
Apart from this, the plugin works amazingly, so hats off to Aidurber for this great work.
Any resolution would be greatly appreciated!

**Comment by Aidurber** [comment]
Thank you for the really detailed bug report, it really helps me understand what's gone wrong and how to reproduce it. I've got a PR for this, I had to rewrite a bunch of stuff to make this work. I'll try and get it released today.

**Comment by Aidurber** [comment]
@SebMoore I've released 0.0.19, you can try the new extractor by going into settings and turning on "New heading extraction"


![CleanShot 2021-12-21 at 14 23 31@2x](https://user-images.githubusercontent.com/5732291/146945571-0d20e6f4-5610-4f1b-9754-5126565c8cd4.jpg)


Do you want to give it a go and let me know how it goes?

**Comment by SebMoore** [comment]
@Aidurber it works perfectly - really appreciate all the effort you put into this.
Cheers!

**Comment by Aidurber** [comment]
Awesome @SebMoore, thanks for helping me test this. I'll ship it to every one 🙌
