### ISSUE TITLE
Duplicating numbers

### ISSUE THREAD

**Issue by DutchPete** [Aidurber/obsidian-plugin-dynamic-toc#3]
First of all thanks for a very useful, yet beautifully simple to use plug-in.

Before installing it I had the [*number headings*](https://github.com/onlyafly/number-headings-obsidian/) plug-in installed, which adds numbers to the headings in the text. Those numbers are then also shown in the Outline pane, useful for navigating long notes with many headings, which my main vault consists of.

When I add a ToC at the top of a note with your plug-in, those pre-inserted numbers, which are part of the heading, also appear in 'your' ToC, thus duplicating the numbers.

![image](https://user-images.githubusercontent.com/10794265/131224626-8f87dd15-b2c5-4113-927b-cf9248980746.png)

Now, I don't know whose issue this is, so I have also [asked about this](https://github.com/onlyafly/number-headings-obsidian/issues/2#issuecomment-907640894) on the other plug-in's *Issues* page.

Both plug-ins are very useful for me, and very easy to use.
Please advise.

**Comment by Aidurber** [comment]
I'll have to investigate this, I'm not sure what the best course of action is here. My presumption is that that the other plugin does this work at render, which means that when the ToC are generated it's reading the already updated headings. 

I'll investigate to see what I can do, but I can't promise anything I'm afraid.

**Comment by DutchPete** [comment]
I understand, and that is the reason why I have raised the issue with the other dev too.
Thanks for your consideration of the issue.

**Comment by Aidurber** [comment]
@DutchPete Upon looking into how number headings. I don't think either library needs to add compatibility with each other. 
This issue you're facing can be tackled with a CSS snippet. 

```css
/* This will hide the number element from the generated table of contents */
.dynamic-toc ol {
  list-style: none;
}
```

1. In your vault, create a CSS snippet "[vault]/.obsidian/snippets/toc-compat.css"
2. Paste the above CSS snippet I've provided
3. Go to Settings -> Appearance
4. Scroll to CSS Snippets at the bottom
5. Hit the refresh button
6. Turn on the toc-compat.css snippet. 

![image](https://user-images.githubusercontent.com/5732291/132984247-24202a89-15ef-4243-ac80-4f0783489773.png)

----

The alternative is that the creator of number-headings rearchitects their code to use a Markdown postprocessor to add the headings for preview mode with a `sortOrder` of some arbitrary higher number than zero. Which I don't think is worthwhile for the developer when it can be resolved on a case by case basis with CSS.

**Comment by DutchPete** [comment]
Yep, that works fine, Andrew.
I also agree that with such a simple solution there is no need to bother the other creator with a request for convoluted programming !
Many thanks for your help and patience.

**Comment by Aidurber** [comment]
@DutchPete I'm glad that solution works for you! Thanks!
