### ISSUE TITLE
Spacing issue in live preview mode

### ISSUE THREAD

**Issue by tcsavage** [Aidurber/obsidian-plugin-dynamic-toc#33]
When using Obsidian's new Live Preview edit mode, the table of contents is _way_ more spaced-out when compared with reading mode (to an uncomfortable degree in my opinion). My expectation is that the TOC should look more-or-less the same spacing-wise between live preview and reader mode. Lists generated by other plugins (e.g. Dataview) do not exhibit this problem for me.

I've included a screenshot showing the same file in edit mode (source), edit mode (live preview) and reader mode:

![Screenshot from 2022-01-02 14-44-19](https://user-images.githubusercontent.com/134930/147880042-8e19ca39-1812-4752-9b22-a477e1f3fdbe.png)

Things I've tried (without success):
- Switching-back to the default theme
- Disabling all CSS snippets
- Disabling all other plugins

I'm running Obsidian v0.13.17 (installer v0.13.14) on macOS and Linux. I've observed this behaviour throughout the v0.13.x release cycle.

**Comment by Aidurber** [comment]
Yeah, I noticed this too when testing out live preview. Didn't think much of it, I'll take a look to see if there is anything I can do. Thanks for the report

**Comment by Aidurber** [comment]
I'm confused by this. I've generated a list with Dataview, and it's working fine. ToC still has massive gaps between everything. 

I've compared the output HTML between DV and ToC and it's almost identical. The only difference being that links are wrapped in `span`, I tried that and it appeared the same. Even the CSS for the rendered elements is identical. 

I also use the same mechanism that DV uses `MarkdownRenderer.renderMarkdown()` I'm rendering valid Markdown. 

Dataview is also experiencing this issue in certain scenarios:  
https://github.com/blacksmithgu/obsidian-dataview/issues/743

I'm going to have to put this on hold and presume it's a bug with Live Preview 🤷

**Comment by tcsavage** [comment]
Interesting. I don't use dataview a lot, but the problem hadn't yet presented to me in the couple of dataview blocks I use. Worth keeping an eye on. I appreciate you taking a look for me. Cheers!

**Comment by tcsavage** [comment]
Based on [a comment on the dataview issue](https://github.com/blacksmithgu/obsidian-dataview/issues/743#issuecomment-1007879013) I created a CSS snippet which fixes the problem for me:

https://gist.github.com/tcsavage/baee0634e6041d6f9773076d12b1e419

Basically copy-and-paste from the [Admonition CSS](https://github.com/valentine195/obsidian-admonition/blob/ebc55b1a3454e7b0cc2949e3278bcc0f91d4a9f0/src/assets/main.css#L273).

**Comment by Aidurber** [comment]
@tcsavage I've release 0.0.23, that seems to have resolved the issue. I'm going to close this ticket, feel free to comment again if you still experience issues with it.

**Comment by future0906** [comment]
Hi, this problem still occur in new release plugin(release-0.0.26)，and obsidian version is v0.13.23.

I had tried open with a complete new vault, and installed only toc plugins, theme using default(light/dark).That didn't fix.

I also tried tcsavage's snippets, still not work.Any idea?

**Comment by future0906** [comment]
This is odd problem.I don't think it's a css issue.
First, the gap is selectable, like pic below:
![image](https://user-images.githubusercontent.com/1061481/153533318-a5cef4e8-fe2b-400f-8ce7-2093a27addd8.png)

Second, I tried using console, editing <ol> html and remove all it's line break in html, it works, the gap is disappear.
![image](https://user-images.githubusercontent.com/1061481/153533395-d9d8ea9d-fbb1-483a-9087-515612d460ae.png)
![image](https://user-images.githubusercontent.com/1061481/153533474-d1618f0e-e09c-4a79-88d9-031588858469.png)

Most rear thing is, in preview mode, ol html code do have line break, but some how don't affect the element

**Comment by future0906** [comment]
OK，I think I got the problem.It's similar to tcsavage's solution, but his css white-space attribute is only for <ul>, this is <ol>.

Problem solve by assign <ol>'s white-space attribute
