### ISSUE TITLE
FR: Mixed List style

### ISSUE THREAD

**Issue by chrisgrieser** [Aidurber/obsidian-plugin-dynamic-toc#35]
Thanks for this plugin! I was about to write a longer dataviewjs query, but this plugin does the job much better anyway :)

I was wondering, is it possible to have an option in the settings / code block for mixed list styles? e.g. H2 numbered, but H3 bullets?

**Comment by Aidurber** [comment]
Interesting, I'm not entirely sure I'll have to look into it, but in the mean time lets work through how it would work @chrisgrieser. 

What happens with a structure like this: 

H2 - Numbered
H3 - Bullets
H4 - ??
H2 - Numbered

Is it just the highest level going bullets and then numbered? 

What would the settings look like for that?
````markdown
```toc
	style: varied
    outer_style: bullet
```
````
We'd need a way to: 
1. Differ from the existing styles that control the entire ToC
2. Specify the "outer" style (bad name)

**Comment by chrisgrieser** [comment]
I'd say if you select a mixed list style, you have to specify for each heading level whether it is gonna be numbers or bullets.

**Comment by Aidurber** [comment]
I think this would make this project much more complicated, having a different setting for each level. I'll look into doing something just to configure the top most level. 

1. If you set "style" to bullet
2. And you set "varied_layout" to true
3. Then the first level will be bullet and the rest will be number and vice versa. 


Then if that works, that is our MVP. I can then play around with the implementation to try and find clean way to build this feature.

**Comment by chrisgrieser** [comment]
Thx 😄

**Comment by Aidurber** [comment]
Released MVP in 0.0.26, let me know if that's all good for you @chrisgrieser

**Comment by chrisgrieser** [comment]
works as intended 👍
