### ISSUE TITLE
Embedded notes shows parent's Dynamic Table of Content

### ISSUE THREAD

**Issue by Write** [Aidurber/obsidian-plugin-dynamic-toc#4]
As the title state, if an embedded note have a DoC, it's the parent's DoC that is injected on top of the embedded note instead of the embedded note DoC itself.
Also, an option to hide embedded notes DoC would be cool.

**Comment by Aidurber** [comment]
Interesting, thanks for sharing @Write. Could you please upload a screenshot to this issue, please?

**Comment by Write** [comment]
Can't easily screenshots because i'm too lazy to strip down private informations, but i tried to open two pans, and embed the second pan into the first one an both have a Dynamic Toc, the second Pan will update with the first pan's dynamic toc too.

**Comment by Aidurber** [comment]
This should be fixed in version 0.0.10. Please feel free to download that release whilst this is still in code review.

**Comment by Aidurber** [comment]
It's been approved. I'm not sure when that becomes available to download as a community plugin.
