### ISSUE TITLE
Feature request: Inline links

### ISSUE THREAD

**Issue by charlesroper** [Aidurber/obsidian-plugin-dynamic-toc#42]
Love this!

Just wondering if it would be possible to add an `inline` option to the styles? This would render a navbar style ToC, something like this:

`Item 1  |  Item 2  |  Item 3  | Item 4`

Perhaps let people specify the delimiter, too?

Here is what the header of my daily notes look like. The to-do and notes links are generated by dynamic toc. You can see why I immediately wanted an inline ToC. :)

Many thanks!

![2022-02-02_01](https://user-images.githubusercontent.com/176/152079388-eebd01db-cea0-40e5-b853-c288b1f96b69.png)

**Comment by Aidurber** [comment]
Hmm, one part of me saying "it's not really in the scope of this project", and the other is saying "it's just a new style"

Leave it with me and I'll see what I can do.

**Comment by Aidurber** [comment]
Released in 0.0.25

**Comment by charlesroper** [comment]
Haha, wow, I posted this when I went to bed (was thinking about tomorrow's daily) and when I get back to my computer next day, you've already pushed the change. ❤️ 

Have just tried it and it works perfectly. Thank you!
