### ISSUE TITLE
Changing note doesn't change TOC

### ISSUE THREAD

**Issue by oslohes123** [Aidurber/obsidian-plugin-dynamic-toc#48]
When I change a note from one to another in live preview the table of contents doesn't automatically change
This is fixed by clicking on the code block to "refresh" it or by putting into the preview mode in which case it is fine.
Can you make it so that it auto refreshes when you change notes
Here is a link to a video that shows this happening in action

https://mega.nz/file/IqYihL6T#FNKIaqaEWi9INWO9l85Db-fGL8CeSkYR6fw9Ow6Gdt8

https://user-images.githubusercontent.com/61867169/155873758-e10cf6fc-8a4f-46fc-b451-ac3b5fd7e491.mp4

**Comment by Aidurber** [comment]
Fixed in 0.0.27, let me know if it works for you.

**Comment by oslohes123** [comment]
The original issue seems to be fixed, However it has created a new issue in that I can't create a new dynamic table of contents
The one in the video where it isn't working was created after updating the plugin.

The ones that worked before were created before updating the plugin

Uploading 2022-03-05 14-11-46.mp4…

**Comment by Aidurber** [comment]
@oslohes123 Are you sure that's not because of the minimum header depth setting? You're adding level 1 headings here. I've just tested and I can't reproduce this issue when I use level 2+ headings. 

![image](https://user-images.githubusercontent.com/5732291/156888716-51cd3e5f-ac56-43ae-8206-bc1327bda8bc.png)

**Comment by oslohes123** [comment]
Ah yes you are correct I didn't see that since I had it set before to 1 but it got changed upon updating, so yeah everything is working as intended, thanks for fixing

**Comment by Aidurber** [comment]
No problem, glad it's all working!
