### ISSUE TITLE
Could not find this plugin over community plugin?

### ISSUE THREAD

**Issue by lawweiliang** [Aidurber/obsidian-plugin-dynamic-toc#5]
Hi @Aidurber, <br>

Thanks for your time in creating such amazing plugins. 

I am trying to search `obsidian-plugin-dynamic-toc` over the search box, nothing seems to show up.

### Print Screen
![image](https://user-images.githubusercontent.com/34936929/132057677-d6fc8ba7-e880-4822-adbc-f96e0f64b279.png)

**Comment by nkoder** [comment]
I think here you can see PR which adds `obsidian-plugin-dynamic-toc` to that searchable list 👉  https://github.com/obsidianmd/obsidian-releases/pull/449 . It's not merged yet.

**Comment by Aidurber** [comment]
@nkoder Is right, it's still in code review. The reviewer found some problems that I need to get around to fixing.

**Comment by lawweiliang** [comment]
Noted @nkoded and @Aidurber.
