### ISSUE TITLE
Skip headings in toc

### ISSUE THREAD

**Issue by StephanReti** [Aidurber/obsidian-plugin-dynamic-toc#54]
Is it possible to skip the first n headings in the toc?

Many of my documents look somewhat like this (in this case I would like to exclude "This is the document title" and "Table of contents" from the toc):
<img width="527" alt="image" src="https://user-images.githubusercontent.com/54271246/159470551-adf9de5c-3c19-4877-a04a-a28b8eb64ab4.png">

My source looks like this:
````
# This is the document title
#TheseAreDocumentTags

# Table of contents
```toc
    style: bullet
    min_depth: 1
    max_depth: 3
```

# First topic
## Subtopic 1

## Subtopic 2

# Second topic
````

**Comment by Aidurber** [comment]
Make "This is the document title" and "Table of contents" level 1 heading, remove `min_depth: 1`, and update the settings page to make sure the min depth is 2.

**Comment by StephanReti** [comment]
Thanks for the quick response. This is certainly a decent solution, however it would require to add a hashtag to every following heading, subheading, ... in the document.
Not that this is a particularly big problem, just a little inconvenience that "clutters" the document.
