### ISSUE TITLE
generate a separate toc for each topics

### ISSUE THREAD

**Issue by lbgws2** [Aidurber/obsidian-plugin-dynamic-toc#55]
I want to put multiple topics in one note, which means that one note contains multiple note contents, and separate lines are used between multiple notes. When I want to generate toc for multiple notes, inline mode always generates all toc, which is not what I want. I want to generate a separate toc for each note.Or from another point of view, generate toc only for the current title and subordinate titles

my note like this 

```
## github

### proxy
### stars project


----

## vim

### plugin
### vimrc
```

**Comment by Aidurber** [comment]
Whilst I do like this suggestion, this plugin aims to just be a standard table of contents without any non-standard magic involved.
