### ISSUE TITLE
Is there a way to have TOC start with a single # and not the double ##?

### ISSUE THREAD

**Issue by BlissfulTarpon** [Aidurber/obsidian-plugin-dynamic-toc#56]
Hello and thank you for developping this. I just moved from Joplin, and there I had most of my title start with a single pound sign. My TOC there would pick this up as the first title but here I need two to have it recognized. Is there a way to change this behavior?

Example:
Joplin this would be

First Title
  Second

/# First Title

/## Second

But on Obsidian I get

Second

/# First Title

/## Second

**Comment by Aidurber** [comment]
Yes, you can use the min depth setting.
