### ISSUE TITLE
Navigating to heading with keyboard

### ISSUE THREAD

**Issue by rappie** [Aidurber/obsidian-plugin-dynamic-toc#57]
I use Obsidian with keyboard only. When I navigate my cursor to the TOC it changes into the code block, making it impossible to jump to the heading i want.

Any ideas how to do this? Thanks.

**Comment by Aidurber** [comment]
@rappie That sounds like an issue with Live Preview to me. All I can suggest is to disable live preview and see if that works.

**Comment by rappie** [comment]
Thanks for the suggestion. It doesn't work but i'll manage without :smile:
