### ISSUE TITLE
Tab and space difference in code blocks

### ISSUE THREAD

**Issue by cjunekim** [Aidurber/obsidian-plugin-dynamic-toc#61]
Hi

Look at the following example:

````
```toc
	style: number
	min_depth: 1
```
````

If the indentation for options is made from a tab character, this isn't parsed at all and resorts to the default values. However, if the identation is made from spaces(4 spaces, for example), it gets parsed and works.

Is this expected?

**Comment by Aidurber** [comment]
@cjunekim YAML (which is what makes up a code block) forbids tabs. 
> Tabs have been outlawed since they are treated differently by different editors and tools. And since indentation is so critical to proper interpretation of YAML, this issue is just too tricky to even attempt. Indeed Guido van Rossum of Python has acknowledged that allowing TABs in Python source is a headache for many people and that were he to design Python again, he would forbid them. ([source](http://yaml.org/faq.html))

So use spaces. I'll update the examples in the README
