### ISSUE TITLE
Want to indent TOC levels without bullets or numbers

### ISSUE THREAD

**Issue by korm** [Aidurber/obsidian-plugin-dynamic-toc#68]
I want my TOCs to use indented levels, without bullets or numbers.   Like this:

Level 1
....Level 1.1
.... ....Level 1.1.1
Level 2
.... Level 2.1

(The dots represent space; I'm not looking to show the dots in real life.)

I don't care if tabs or spaces are used.   I cannot see a way to make this happen in the Dynamic TOC settings.   I'm using the Minimal Style and the Style Settings Plugin, so maybe there's a way there.  I'm just looking for a starting point for setting this up.

(It sure seems to me that Dynamic TOC used to work this way and then something changed; but that might just be false memory.)

**Comment by Aidurber** [comment]
@korm that sounds like a false memory to me. The ToC is generated using markdown lists. so it should be possible to hide the indicators using some CSS.

If you add a custom CSS snippet inside `.obsidian/snippets/` you can make this work. 

You can use this snippet: 
```css
.dynamic-toc ol, .dynamic-toc ul {
    list-style: none;
}
```

1. Create a CSS file inside the snippets directory such as `.obsidian/snippets/list-hider.css`
2. Set the contents of `list-hider.css` to the above CSS
3. Go to obsidian settings -> Appearance -> Select list-hider.css from the list at the bottom

I don't think this is a common enough request to add it to the plugin officially, so I suggest you make the change on your end. 

I hope this helps.
