### ISSUE TITLE
Position of TOC is strange after exporting PDF

### ISSUE THREAD

**Issue by hisaito** [Aidurber/obsidian-plugin-dynamic-toc#7]
The position of TOC is different between preview and PDF.
The position in preview mode is correct, and the position in PDF is wrong.

**Comment by Aidurber** [comment]
I'm going to need an example: 
1. Which syntax are you using? ```toc or "External Rendering" 
2. A screenshot

Here's what it looked for me which is correct. 

![image](https://user-images.githubusercontent.com/5732291/133927291-febf2cee-5f9e-4b0c-ab3f-83653a024ccd.png)
