### ISSUE TITLE
Additional rendering support requests

### ISSUE THREAD

**Issue by korm** [Aidurber/obsidian-plugin-dynamic-toc#9]
DEVONthink uses this format for table of contents -- please support it:

{{toc}}

TheBrain uses this format for table of contents -- please support it:

[/toc/]

**Comment by Aidurber** [comment]
Thanks for listing these. That should now be live in version 0.0.12

**Comment by korm** [comment]
Thanks for the quick update @Aidurber !!  I wish you had a  [Buy Me a Coffee](https://www.buymeacoffee.com/) page.

**Comment by Aidurber** [comment]
This is just a hobby for me, I can pick it up and stop when I want to. When money crosses hands it stops being a hobby and there is an implicit obligation. 

I really appreciate it, but a promise you a "thank you" is more than enough for me, I just like making tools 😄
